apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cravo-helm-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/akgupta-47/cravo-helm
    targetRevision: main
    path: cravo-helm
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
