apiVersion: apps/v1
kind: Deployment
metadata: 
  name: "{{ .Release.Name }}-deployment"
  labels:
    app: go-pod
spec: 
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels:
      app: go-pod
  template: 
    metadata:
      labels:
        app: go-pod
    spec:
      containers:
        - name: pod-test
          image: "{{ .Values.deploy.image.repository }}:{{ .Chart.AppVersion }}"
