apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
  labels:
    app: go-pod
spec:
  selector:
    app: go-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
